FROM nginx:latest

RUN rm /etc/nginx/conf.d/default.conf
ADD conf/default.conf /etc/nginx/conf.d/default.conf
COPY 50x.html /usr/share/nginx/html/50x.html
COPY 404.html /usr/share/nginx/html/404.html
